name: Update

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update video info
    runs-on: ubuntu-latest
    env:
      DB_KEY: ${{ secrets.DB_KEY }}
      USER_ID_COOKIE: ${{ secrets.USER_ID_COOKIE }}
      LINK_1S_API_KEY: ${{ secrets.LINK_1S_API_KEY }}
      ABYSS_API_KEY: ${{ secrets.ABYSS_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt update
      - run: sudo apt install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - run: npm ci
      - run: npm run update
